### PR TITLE
Update to version 9.1.1

### LINKED ISSUE #12: Update to version 9.1.1
Instead of version 9.0.4 version 9.1.1 should be downloaded and installed.

### PR DESCRIPTION
**Pull request by choeppler**
Update to ownCloud version 9.1.1.

Fixes #12

### CODE REVIEW

**Comment by brejoc** [comment]
Thanks @choeppler, but you've got a typo in the URL. Should be `9.1.1` instead of `9.l.1`.

**Comment by choeppler** [comment]
OOps. Typo should be fixed now...

**Comment by brejoc** [comment]
No worries. Did you push your changes? I'm only seeing your first commit.

**Comment by brejoc** [comment]
@choeppler Oh, I just noticed that you rewrote history. To be honest, I'm not a fan of that feature, because Github isn't showing that properly.

But thanks, for your contribution! I'm now merging your change.

**Comment by choeppler** [comment]
@brejoc Sorry for the confusion. Yes, I force updated the branch the pull request was based upon so as not to clutter your history with some odd typo...

**Comment by brejoc** [comment]
@choeppler Github allows to [squash](https://github.com/blog/2141-squash-your-commits) commits from a pull request very easily now. So you don't have to worry.

**Pull request merged**
